- name: Demonstrate use of docker_container ansible module
  hosts: localhost
  tasks:
    - name: Start the ubuntu container
      docker_container:
        name: "ubuntu{{item}}"
        hostname: "ubuntu{{item}}"
        image: verizon/ansible-ubuntu
        state: started
        ports:
           - "200{{item}}:22"
           - "800{{item}}:80"
      with_sequence: start=1 end=5
    
    - name: Remove the ubuntu container
      docker_container:
        name: "ubuntu{{item}}"
        hostname: "ubuntu{{item}}"
        image: verizon/ansible-ubuntu
        state: absent
        ports:
           - "200{{item}}:22"
           - "800{{item}}:80"
      with_sequence: start=3 end=5

    - name: Start the centos container
      docker_container:
        name: "centos{{item}}"
        hostname: "centos{{item}}"
        image: verizon/ansible-centos
        state: started
        ports:
           - "300{{item}}:22"
           - "900{{item}}:80"
      with_sequence: start=1 end=5
