---
- name: Configure nginx web root folder Ubuntu
  when: ( ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" )
  copy: src=default dest=/etc/nginx/sites-available/default

- name: Configure nginx web root folder CentOS
  when: ( ansible_os_family == "RedHat" and ansible_distribution == "CentOS" )
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
   
- name: Create the web root folder
  file: path=/var/html state=directory mode=0777
  notify: 
     - Restart nginx server
...
